version: "3.3"

services:
  sale-service-backend:
    container_name: sale-service-backend
    build:
      context: .
    ports:
      - "8080:8080"
    networks:
      - backend
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: "sale-system"
      MYSQL_USER: "yan"
      MYSQL_PASSWORD: "yan"
      MYSQL_ROOT_PASSWORD: "zingra"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ./.docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend
networks:
  backend:
    driver: bridge
