version: "3.3"
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: "sale-system"
      MYSQL_USER: "yan"
      MYSQL_PASSWORD: "yan"
      MYSQL_ROOT_PASSWORD: "zingra"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ./.docker/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  my-db:
